### ISSUE TITLE
Error: exited with error code: 1

### ISSUE THREAD

**Issue by massaoiwanaga** [ricardomansano/reactron#4]
Boa noite caro Ricardo.

Estou tomando esse erro ao dar 'npm start' / 'yarn start' no reactron. Já tentei voltar para versões anteriores o "end-of-stream", o "gulp", o node e até o npm, mas nada deu certo. O pior é que em outros computadores funciona, mas no meu não! Tem ideia do que pode ser? 

![Erro reactron](https://user-images.githubusercontent.com/49959318/78943777-e0969400-7a92-11ea-8070-d3eb3861e7ae.PNG)

**Comment by ricardomansano** [comment]
Boa noite Massao,

Outro colega teve o mesmo problema e verifiquei que era os espaços no diretório do projeto.

Isso começou a acontecer depois de uma das atualizações de segurança, só não sei dizer em que LIB.

Clone ou mova o projeto pra um caminho sem espaços que vai conseguir rodar a aplicação.
