### ISSUE TITLE
Dificuldade para importar arquivos

### ISSUE THREAD

**Issue by massaoiwanaga** [ricardomansano/reactron#5]
Ricardo, 

Primeiramente obrigado por esclarecer o issue anterior do espaço no caminho do projeto.

Estou tentando fazer uma importação simples no projeto, mas a tela fica em branco!

import myTxt from './teste.txt'

1) Se há algum erro, por que não é discriminado no console? 2) Por que o react+electron tem essa dificuldade com importação? Como solucionar?

Também já havia encontrado dificuldade para importar um .CSS. Não consegui. Tive que acabar importando no index.html.

Valeu!

**Comment by ricardomansano** [comment]
Boa tarde Massao,
Confesso que sou do mundo C++, me aventurei aqui por pura diversão...
E dado tempo da sua pergunta com certeza ja resolveu o problema.

Pelo que sei do import ele não é usado desta forma, capturando o conteudo de um arquivo.
No fs_inifile.js fiz algo parecido com o que precisa

Procura pelo que usei no FS
var fs = require('fs')
