### ISSUE TITLE
Tela em branco ao criar executável com o "electron-packager"

### ISSUE THREAD

**Issue by massaoiwanaga** [ricardomansano/reactron#6]
Boa noite Ricardo,

Usei a biblioteca "electron-packager" para gerar um executável do projeto, mas ao executar o arquivo .EXE gerado a tela abre em branco! Qual biblioteca vc usou para gerar o executável dele?

Obrigado!

**Comment by ricardomansano** [comment]
Boa tarde Massao,

No gulpfile.js do projeto vc pode ver o codigo completo, mas usei o electron-builder

gulp.task('dist', gulp.series('build', () => {
    return exec(
        __dirname+'/node_modules/.bin/electron-builder .'
    ).on('close', () => process.exit());

**Comment by Jhoelber** [comment]
Ja faz muito tempo... kkkk Mas conseguiu resolver o problema da tela branca? Estou passando pelo mesmo problema

**Comment by ricardomansano** [comment]
Bom dia @Jhoelber , fazia tempo que nao baixava o projeto, tá bem defasado, mas aqui em Linux não tive problemas.
confesso que não vou conseguir olhar isso agora, tô de férias, mas qqer coisa abre uma issue nova que alguem pode ter alguma ideia.

![image](https://github.com/ricardomansano/reactron/assets/33813921/9db11a5c-f752-4fcc-80b5-a868bde9a0cc)
